apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webApp-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: sample-webApp
  template:
    metadata:
      labels:
        role: sample-webApp
    spec:
      containers:
      - name: sameple-webApp-c
        image: "{{ image_id }}"
        resources:
          requests:
            cpu: 10m
